all: cpu
run: a.out
cpu.o: cpu.c
	gcc -c cpu.c
dump_memory.o: dump_memory.c
	gcc -c dump_memory.c
execute.o: execute.c
	gcc -c execute.c
fetch_decode.o: fetch_decode.c
	gcc -c fetch_decode.c
load_mem.o: load_mem.c
	gcc -c load_mem.c
test_mem.o: save_mem.c
gcc -c sav_mem.c
test_device.o: test_device.c
    gcc -c test_device.c

	gcc -c read_device.c
	gcc -c write_device.c
	gcc -c dump_memory.c
